version: "3"
services:
  web:
    image: javawolfpack/cins465web:latest
    #build: code
    depends_on:
       - postgres
    
    expose:
      - "8000"
#     ports:
#        - "8000:8000"
    links:
      - postgres:postgres
#     volumes:
#       - ./code/:/code/
#     #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn -w 2 -b :8000 myproj.wsgi
    
#   nginx:
#     restart: always     
#     #build: ./nginx/
#     image: javawolfpack/cins465nginx:latest
#     depends_on:
#       - web
#     ports:
#       - "80:80"       
#       - "443:443"
# #     volumes:
# #        - ./code/static:/static
#     links:
#       - web:web

  nginx:
    restart: always
    image: nginx
    depends_on:
      - web
    links:
      - web:web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/mysite.template
      - ./nginx/ssl/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./db/postgresql:/var/lib/postgresql
    expose:
      - "5432"