# Generated by Django 2.0.1 on 2018-02-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion_model',
            name='suggestion',
            field=models.CharField(max_length=240),
        ),
    ]
