# Generated by Django 2.0.1 on 2018-04-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180403_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion_model',
            name='image',
            field=models.ImageField(default='null', max_length=144, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion_model',
            name='image_description',
            field=models.CharField(default='NO IMAGE', max_length=240),
            preserve_default=False,
        ),
    ]
